# fly.toml file generated for news-notifier on 2022-10-03T23:35:14+05:00

app = "news-notifier"
kill_signal = "SIGTERM"
kill_timeout = 10

[build]
  builder = "heroku/buildpacks:latest"

[deploy]
  release_command = "python3 db.py"

[env]
  PORT = "8080"
