# fly.toml file generated for news-notifier on 2022-10-05T16:39:04+05:00

app = "news-notifier"
kill_signal = "SIGINT"
kill_timeout = 60
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

#deploy]
#  release_command = "python3 db.py"
